"""petimage deleted

Revision ID: 73914275fac8
Revises: 616da4542c98
Create Date: 2025-05-01 18:10:31.347659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73914275fac8'
down_revision = '616da4542c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet_images')
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet_picture', sa.String(length=200), nullable=True))
        batch_op.drop_column('interests')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('pet_picture')

    op.create_table('pet_images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pet_id', sa.INTEGER(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=256), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
